name: programming_memo_for_mac_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274

  flutter_app_name:
    git:
      url: https://github.com/f-prime/flutter_app_name
      ref: fcd55ef026ae00ce95e1083d928d54f02a570fae

  hooks_riverpod: any
  state_notifier: any
  freezed_annotation: any
  flutter_markdown: any
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  url_launcher: ^6.1.0
  universal_io: ^2.0.4
  auto_size_text: ^3.0.0
  icons_launcher: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  pedantic_mono:
  build_runner:
  freezed:
  json_serializable:
  mockito:
  hive_generator: ^1.1.2
  hive_test: ^1.0.1

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  image_path: 'assets/app_icon.png'
  image_path_macos: 'assets/app_icon.png'
  remove_alpha_macos: false
  android: false
  ios: false
  macos: true

flutter_app_name:
  name: "メモ for markdown"
